[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"
rootDirectory = "frontend"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
XMTP_RELAY_URL = https://https://worldmarket-frontend-production.up.railway.app/