[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
solc_version = "0.8.24"
offline = false
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "world-id-contracts/=lib/world-id-contracts/src/",
]

[profile.default.fuzz]
runs = 100
